### ISSUE TITLE
Название каталога для разбора правил

### ISSUE THREAD

**Issue by pallid** [otymko/gitrules#17]
При разборе правил получается что название конечного каталога зависит от названия файла правил

т.е если мы все правила называем одинаково, например "ПравилаОбменаДанными.xml" и при разборе  место для выгрузки указываем ./exchange/ПравилаУТРозница/ получается что путь становится  ./exchange/ПравилаУТРозница/ПравилаОбменаДанными.xml/

а хотелось бы ./exchange/ПравилаУТРозница/ и в нем весь разбор

или это только у меня такая проблема?

**Comment by otymko** [comment]
Можно сделать доработку:
```
gitrules export -h ExchangeRules.xml ./src
```
Опция -h / -here будет определять что файл правил нужно выгрузки просто в каталог.

Если имелось ввиду глобальный механизм, при precommit или при git commit - от этого не уйти. У меня например, в папке с проектом git может быть файл ПравилаОбмена.xml и рядом еще каталог с вложенными правилами ПравилаОбмена. В таком случае при разборе возникают проблемы.

**Comment by otymko** [comment]
@pallid Это имелось ввиду? https://github.com/otymko/gitrules/releases/tag/0.2.3

**Comment by pallid** [comment]
@otymko да, спасибо

**Comment by otymko** [comment]
@pallid в выходные рабочую сборку сделаю и в hub запушу.
