### ISSUE TITLE
Ошибка при разборке правил

### ISSUE THREAD

**Issue by NoRazum** [otymko/gitrules#19]
Название каталог берется из наименования в КД2 в рознице 2.2.10 в правилах конвертации
название "Справочник: Кассы ККМ" и при создание такого каталога падает с ошибкой
{Модуль C:\Program Files (x86)\OneScript\lib\gitrules\src\core\Модули\РазобратьПравилаОбмена.os / Ошибка в строке: 151 / Внешнее исключение (System.NotSupportedException): Данный формат пути не поддерживается.} 
Двоеточия запрещены.
Можно исправить такую ошибку?

**Comment by otymko** [comment]
Да, попробую завтра посмотреть

**Comment by otymko** [comment]
@NoRazum Покажите как правило выглядит. Пример:
![image](https://user-images.githubusercontent.com/11651847/48495294-419c4700-e862-11e8-8062-45313ec19d30.png)
У меня не удалось в имя правила двоеточие поставить.

**Comment by otymko** [comment]
@NoRazum В текущем релизе из наименований убираются запрещенные символы. Можно проверить как работает.

**Comment by NoRazum** [comment]
Благодарю. Это решилось.
Осталось проблема длины пути. Но это другая тема.
