### ISSUE TITLE
Конфликт при коммите в SourceTree

### ISSUE THREAD

**Issue by korolevpavel** [otymko/gitrules#20]
Процесс работы:
1) Файлы правил сохраняются в каталог
2) Индексирование и коммиты идут через SourceTree

В случае, если использовать хук как есть - коммиты через SourceTree не отправляются и вылетает ошибка:

```
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks -c credential.helper= -c credential.helper="C:/Users/Korolev/AppData/Local/ATLASS~1/SOURCE~1/GIT_EX~1/GIT-CR~1.EXE" commit -q -F C:\Users\Korolev\AppData\Local\Temp\1y2burf1.1es
Start
Запущен менеджер правил

START precommit gitrules
FILE: D:\repo1c\ПравилаОбменаДанными.xml
Add to index git
{Модуль C:\Program Files (x86)\OneScript\lib\1commands\src\Команда.os / Ошибка в строке: 308 / Внешнее исключение (System.ArgumentException): Элемент уже добавлен. Ключ в словаре: "HOME"  Добавляемый ключ: 'home'}
Выполнено с ошибками, см. выше.
```
Чтобы уйти от ошибки - закомментировал код 
![image](https://user-images.githubusercontent.com/12083359/51969313-231f1280-2485-11e9-9465-5b09acebccbc.png)

Но в итоге получилось что сначала идет отправка коммита с неразобранным файлом правил, после коммита происходит разбор и новые файлы заново индексирую через SourceTree.

Я так понимаю, здесь нужно использовать что-то отличное, то git *, так как неразобранный файл правил проиндексированный через SourceTree заново индексируется через хук:
```
Процедура ДобавитьПравилаВИндексGIT() Экспорт
	Команда = Новый Команда;
	Команда.УстановитьРабочийКаталог(ОсновнойКаталогПравил);
	Команда.УстановитьКоманду("git add *");
	КодВозврата = Команда.Исполнить();
КонецПроцедуры

```

**Comment by otymko** [comment]
Можно попробовать версия 1.1.0 (через opm install gitrules)

**Comment by korolevpavel** [comment]
> Можно попробовать версия 1.1.0 (через opm install gitrules)

Пока воспроизводится. Проверил что обновлено, скорректировав вывод сообщения.
![image](https://user-images.githubusercontent.com/12083359/52133552-9b86fe80-2652-11e9-9bf1-37cdef2c4271.png)
Получил:
![image](https://user-images.githubusercontent.com/12083359/52133562-9e81ef00-2652-11e9-8d3f-e284021345da.png)

**Comment by otymko** [comment]
Странно.. Сегодня поставил из коробки sourcetree и не было такого

**Comment by korolevpavel** [comment]
Заработало, после 
`opm install 1commands`
