### ISSUE TITLE
Ошибка при разборке правил

### ISSUE THREAD

**Issue by AlexPCRus** [otymko/gitrules#21]
Start
Запущен менеджер правил
START precommit gitrules
...
{Модуль C:\Program Files (x86)\OneScript\lib\gitrules\src\core\Модули\РазобратьПравилаОбмена.os / Ошибка в строке: 150 / Внешнее исключение (System.ArgumentException): Illegal characters in path.}
Done

**Comment by otymko** [comment]
@AlexPCRus нужно больше данных, чтобы понять в чем проблема. Нужно в файл РазобратьПравилаОбмена.os вставить код на строке 150 как у меня на скриншоте:

![image](https://user-images.githubusercontent.com/11651847/52045175-7e7cfd80-2576-11e9-9cb9-2a50c26645ef.png)

После этого в консоли можно понять на каком идентификаторе объекта падает алгоритм.

**Comment by AlexPCRus** [comment]
Start
Запущен менеджер правил
START precommit gitrules
Произошла проблема объединения путей. Текущий каталог C:\Users\...\Git\buh_rules\src\ОбменВсеДанные_ПравилаРегистрацииОбъектов.xml\ПравилаРегистрацииОбъектов\Регистры накопления. Идентификатор объекта Расходы на "Платон"
Произошла проблема объединения путей. Текущий каталог C:\Users\...\Git\buh_rules\src\ОбменВсеДанные_ПравилаРегистрацииОбъектов.xml\ПравилаРегистрацииОбъектов\Документы. Идентификатор объекта Отчет оператора системы "Платон"
{Модуль C:\Program Files (x86)\OneScript\lib\gitrules\src\core\Модули\РазобратьПравилаОбмена.os / Ошибка в строке: 105 / Внешнее исключение (System.IO.PathTooLongException): The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.}
Done

**Comment by AlexPCRus** [comment]
Кавычки надо обрабатывать или заменять на другие символы

**Comment by otymko** [comment]
Можно попробовать вот эту сборку https://github.com/otymko/gitrules/releases/download/0.2.3-beta/gitrules-0.2.3.ospx .
Установка через консоль:
`opm install -f  **/path/to/file/gitrules-0.2.3.ospx**`

**Comment by otymko** [comment]
Есть в релизе, можно пользоваться
