### ISSUE TITLE
Основа приложения на cli

### ISSUE THREAD

**Issue by khorevaa** [otymko/gitrules#3]
Как сморишь на то чтобы сделать отдельно `core` - библиотека работы с правилами 
`cmd` - приложение на основании [cli](https://github.com/khorevaa/cli)

Примеры реализации:
* https://github.com/silverbulleters/ovm
* https://github.com/oscript-library/gitsync/tree/develop

При таком подходе будет сразу и либа и приложения. И возможно встраивание в другие приложения твоей либы по разбору и сборке(?) правил

**Comment by otymko** [comment]
У меня были такие мысли. Но сначала нужно сборку правил доделать и тестами обложить основной функционал. Так же с правилами регистрации сборку / разборку я пока только в прототипе начал обрабатывать.

**Comment by otymko** [comment]
@khorevaa, изначально использовался шаблон консольного приложения (https://github.com/EvilBeaver/oscript-app-template). Добавил в release 0.2.0 возможность через консольное приложение разбирать / собирать правила обмена.
