### ISSUE TITLE
[BUG] Не работает hook и gitrules precommit

### ISSUE THREAD

**Issue by ovcharenko-di** [otymko/gitrules#31]
Имеем пустой репозиторий на Windows, свежую версию gitrules, oscript 1.4

Добавляем xml с правилами в корень репозитория.
Устанавливаем хук `gitrules install`
`git add .`
`git commit -m "init"`
Выдается ошибка (см. скриншот)
Если вызвать напрямую gitrules precommit, ошибка та же.

![image](https://user-images.githubusercontent.com/24920942/102605160-ecfce180-4135-11eb-8263-25d7e8a4cbf7.png)

Однако, при `gitrules export Правила.xml /out` почему-то создается каталог `src` вместо `out`, команда выполняется успешно, но правила не разбираются.

**Comment by korolevpavel** [comment]
У меня была такая же ошибка, почему-то нет метода в модуле, добавил в #32

**Comment by otymko** [comment]
@ovcharenko-di @korolevpavel в 1.1.2 теперь все ок?

**Comment by ovcharenko-di** [comment]
@otymko проверил, работает! и install, и export
